export interface Event {
  id: string
  slug: string
  title: string
  category: string
  date: string
  location: string
  venue: string
  image: string
  priceFrom: number
  priceTo: number
  currency: string
  description: string
  partners: Partner[]
}

export interface Partner {
  name: string
  url: string
  priceFrom: number
  priceTo: number
  note: string
}

export const events: Event[] = [
  {
    id: '1',
    slug: 'fradi-ferencvaros-vs-ujpest-fc-2026',
    title: 'Ferencváros TC – Újpest FC',
    category: 'Labdarúgás',
    date: '2026-05-09',
    location: 'Budapest, Magyarország',
    venue: 'Groupama Aréna',
    image: '/images/event-fradi-ujpest.jpg',
    priceFrom: 3500,
    priceTo: 18000,
    currency: 'HUF',
    description: 'A magyar labdarúgás egyik legizgalmasabb rangadója – a Ferencváros és az Újpest összecsapása a Groupama Arénában. Élvezd a Budapest szívében zajló szenvedélyes derbit.',
    partners: [
      { name: 'Eventim.hu', url: 'https://www.eventim.hu', priceFrom: 3500, priceTo: 18000, note: 'Magyar platform' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 4200, priceTo: 22000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 5000, priceTo: 25000, note: 'Viszonteladói árak' },
      { name: 'Interticket', url: 'https://www.interticket.com', priceFrom: 3800, priceTo: 19500, note: 'Magyar platform' },
    ],
  },
  {
    id: '2',
    slug: 'atp-budapest-open-2026',
    title: 'ATP Budapest Grand Prix',
    category: 'Tenisz',
    date: '2026-05-17',
    location: 'Budapest, Magyarország',
    venue: 'Római-parti Teniszakadémia',
    image: '/images/event-atp-budapest.jpg',
    priceFrom: 4000,
    priceTo: 35000,
    currency: 'HUF',
    description: 'A Budapest Grand Prix az ATP tenisztorna legizgalmasabb hete. Világ top-100-as játékosok küzdenek a döntőért a magyar főváros egyik legszebb teniszkomplexumában.',
    partners: [
      { name: 'Eventim.hu', url: 'https://www.eventim.hu', priceFrom: 4000, priceTo: 35000, note: 'Magyar platform' },
      { name: 'Interticket', url: 'https://www.interticket.com', priceFrom: 4500, priceTo: 38000, note: 'Magyar platform' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 5500, priceTo: 42000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '3',
    slug: 'formula1-hungarian-grand-prix-2026',
    title: 'Formula–1 Magyar Nagydíj',
    category: 'Motorsport',
    date: '2026-08-02',
    location: 'Mogyoród, Magyarország',
    venue: 'Hungaroring',
    image: '/images/event-hungaroring.jpg',
    priceFrom: 25000,
    priceTo: 280000,
    currency: 'HUF',
    description: 'A Hungaroring adott otthont az egyik leglátványosabb F1 nagydíjnak évtizedek óta. Érezd a verseny izgalmát közvetlenül a pályaoldalon, a legjobb tribünökről nézve.',
    partners: [
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 25000, priceTo: 280000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 28000, priceTo: 310000, note: 'Viszonteladói árak' },
      { name: 'Ticketmaster', url: 'https://www.ticketmaster.com', priceFrom: 32000, priceTo: 350000, note: 'Viszonteladói platform' },
      { name: 'Eventim.hu', url: 'https://www.eventim.hu', priceFrom: 35000, priceTo: 380000, note: 'Magyar platform' },
    ],
  },
  {
    id: '4',
    slug: 'ea-sports-fc-champions-league-final-2026',
    title: 'UEFA Bajnokok Ligája – Döntő',
    category: 'Labdarúgás',
    date: '2026-05-30',
    location: 'München, Németország',
    venue: 'Allianz Arena',
    image: '/images/event-champions-league.jpg',
    priceFrom: 150000,
    priceTo: 1200000,
    currency: 'HUF',
    description: 'A kontinens legrangosabb klubfutballtornájának döntője – a Bajnokok Ligája fináléja az Allianz Arénában. Európa legjobb csapatai mérkőznek meg a trófeáért.',
    partners: [
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 150000, priceTo: 500000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 180000, priceTo: 850000, note: 'Viszonteladói árak' },
      { name: 'Ticketmaster', url: 'https://www.ticketmaster.com', priceFrom: 200000, priceTo: 1200000, note: 'Viszonteladói platform' },
    ],
  },
  {
    id: '5',
    slug: 'nba-europe-live-2026',
    title: 'NBA Europe Live – Pre-Season',
    category: 'Kosárlabda',
    date: '2026-10-03',
    location: 'Berlin, Németország',
    venue: 'Mercedes-Benz Arena',
    image: '/images/event-nba-europe.jpg',
    priceFrom: 18000,
    priceTo: 95000,
    currency: 'HUF',
    description: 'Az NBA szezonelőkészítő európai turnéjának egyik állomása – két NBA-csapat mérkőzi meg egymással Berlinben. Egyedülálló élmény az NBA-t élőben látni Európában.',
    partners: [
      { name: 'Ticketmaster', url: 'https://www.ticketmaster.com', priceFrom: 18000, priceTo: 95000, note: 'Viszonteladói platform' },
      { name: 'Eventim HU', url: 'https://www.eventim.hu', priceFrom: 20000, priceTo: 105000, note: 'Hivatalos forgalmazó' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 22000, priceTo: 120000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '6',
    slug: 'wbc-heavyweight-championship-2026',
    title: 'WBC Nehézsúlyú Bajnokság',
    category: 'Ökölvívás',
    date: '2026-06-13',
    location: 'London, Egyesült Királyság',
    venue: 'O2 Arena',
    image: '/images/event-wbc-boxing.jpg',
    priceFrom: 35000,
    priceTo: 450000,
    currency: 'HUF',
    description: 'A WBC nehézsúlyú bajnoki cím odaítéléséért folyó mérkőzés – egy este, két bajnok, számtalan izgalom az O2 Arénában, London szívében.',
    partners: [
      { name: 'AXS Tickets UK', url: 'https://www.axs.com', priceFrom: 35000, priceTo: 450000, note: 'Hivatalos forgalmazó' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 42000, priceTo: 520000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 45000, priceTo: 600000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '7',
    slug: 'world-aquatics-championships-2027',
    title: 'Úszó Világbajnokság',
    category: 'Vízi sportok',
    date: '2027-07-10',
    location: 'Szingapúr',
    venue: 'OCBC Aquatic Centre',
    image: '/images/event-world-aquatics.jpg',
    priceFrom: 12000,
    priceTo: 65000,
    currency: 'HUF',
    description: 'A FINA Úszó Világbajnokság a világ legjobb úszóinak seregszemléje. Drámai döntők, rekordok és felejthetetlen pillanatok várnak.',
    partners: [
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 12000, priceTo: 65000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 14000, priceTo: 72000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '8',
    slug: 'iaaf-world-athletics-championships-2027',
    title: 'Atlétikai Világbajnokság',
    category: 'Atlétika',
    date: '2027-08-14',
    location: 'Tokió, Japán',
    venue: 'Nemzeti Olimpiai Stadion',
    image: '/images/event-athletics-tokyo.jpg',
    priceFrom: 15000,
    priceTo: 120000,
    currency: 'HUF',
    description: 'A világ legjobb atlétiái versenyeznek a 100 méteres sprinttől a maraton döntőig. Legyél ott, amikor új világrekordok születnek.',
    partners: [
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 15000, priceTo: 120000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 17000, priceTo: 135000, note: 'Viszonteladói árak' },
      { name: 'Ticketmaster', url: 'https://www.ticketmaster.com', priceFrom: 20000, priceTo: 150000, note: 'Viszonteladói platform' },
    ],
  },
  {
    id: '9',
    slug: 'ehf-champions-league-final4-2026',
    title: 'EHF BL Final4 – Kézilabda',
    category: 'Kézilabda',
    date: '2026-06-06',
    location: 'Köln, Németország',
    venue: 'Lanxess Arena',
    image: '/images/event-ehf-final4.jpg',
    priceFrom: 22000,
    priceTo: 180000,
    currency: 'HUF',
    description: 'Az EHF Bajnokok Ligájának végső négyes tornája Kölnben – Európa legjobb kézilabdacsapatai mérkőznek a trófeáért a hétvégi látványossággal.',
    partners: [
      { name: 'Eventim HU', url: 'https://www.eventim.hu', priceFrom: 22000, priceTo: 180000, note: 'Magyar forgalmazó' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 25000, priceTo: 195000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 28000, priceTo: 220000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '10',
    slug: 'tour-de-france-2026-paris-finale',
    title: 'Tour de France – Párizsi Döntő',
    category: 'Kerékpározás',
    date: '2026-07-26',
    location: 'Párizs, Franciaország',
    venue: 'Champs-Élysées',
    image: '/images/event-tour-de-france.jpg',
    priceFrom: 5000,
    priceTo: 85000,
    currency: 'HUF',
    description: 'A Tour de France utolsó étapja és díjátadója a világ legszebb körútján, a Champs-Élysées-n. Légy szemtanúja, amikor a sárga mezesek megérkeznek Párizsba.',
    partners: [
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 5000, priceTo: 85000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 7000, priceTo: 95000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '11',
    slug: 'euro-2027-basketball-fiba',
    title: 'FIBA Eurobasket 2027',
    category: 'Kosárlabda',
    date: '2027-09-01',
    location: 'Helsinki, Finnország',
    venue: 'Hartwall Arena',
    image: '/images/event-eurobasket.jpg',
    priceFrom: 8000,
    priceTo: 55000,
    currency: 'HUF',
    description: 'A FIBA Eurobasket 2027 a kontinens legjobb kosárlabda válogatottainak versengése. Európa bajnoki trófeájáért folyik a küzdelem Helsinkiben.',
    partners: [
      { name: 'Ticketmaster', url: 'https://www.ticketmaster.com', priceFrom: 8000, priceTo: 55000, note: 'Viszonteladói platform' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 9000, priceTo: 60000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 10000, priceTo: 68000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '12',
    slug: 'wimbledon-2026-mens-final',
    title: 'Wimbledon – Férfi Döntő',
    category: 'Tenisz',
    date: '2026-07-12',
    location: 'London, Egyesült Királyság',
    venue: 'All England Club – Centre Court',
    image: '/images/event-wimbledon.jpg',
    priceFrom: 55000,
    priceTo: 620000,
    currency: 'HUF',
    description: 'A grand slam bajnokság legszentebb pályáján – a Wimbledon Centre Court-on – dől el, ki viseli a fűpályás tenisz koronáját. Az élmény felülmúlhatatlan.',
    partners: [
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 55000, priceTo: 620000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 65000, priceTo: 720000, note: 'Viszonteladói árak' },
      { name: 'Ticketmaster', url: 'https://www.ticketmaster.com', priceFrom: 70000, priceTo: 800000, note: 'Viszonteladói platform' },
    ],
  },
  {
    id: '13',
    slug: 'magyar-vb-selejtezo-2026',
    title: 'Magyarország – Hollandia VB-selejtező',
    category: 'Labdarúgás',
    date: '2026-09-05',
    location: 'Budapest, Magyarország',
    venue: 'Puskás Aréna',
    image: '/images/event-puskas-hungary.jpg',
    priceFrom: 5000,
    priceTo: 28000,
    currency: 'HUF',
    description: 'A magyar labdarúgó-válogatott hazai VB-selejtezője a Puskás Arénában. Szurkolj a nemzeti csapatnak a 2026-os világbajnoki helyért folyó harcban!',
    partners: [
      { name: 'Eventim.hu', url: 'https://www.eventim.hu', priceFrom: 5000, priceTo: 28000, note: 'Magyar platform' },
      { name: 'Interticket', url: 'https://www.interticket.com', priceFrom: 5500, priceTo: 30000, note: 'Magyar platform' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 7000, priceTo: 38000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '14',
    slug: 'roland-garros-2026-french-open',
    title: 'Roland Garros – Francia Open',
    category: 'Tenisz',
    date: '2026-05-24',
    location: 'Párizs, Franciaország',
    venue: 'Court Philippe-Chatrier',
    image: '/images/event-roland-garros.jpg',
    priceFrom: 18000,
    priceTo: 220000,
    currency: 'HUF',
    description: 'A világ legjobb salakpályás tornája – a Roland Garros. A párizsi agyagpályákon dőlnek el a grand slam nyerők sorsai minden évben.',
    partners: [
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 18000, priceTo: 220000, note: 'Viszonteladói árak' },
      { name: 'Viagogo', url: 'https://www.viagogo.com', priceFrom: 22000, priceTo: 265000, note: 'Viszonteladói árak' },
      { name: 'Ticketmaster', url: 'https://www.ticketmaster.com', priceFrom: 25000, priceTo: 300000, note: 'Viszonteladói platform' },
    ],
  },
  {
    id: '15',
    slug: 'mma-bellator-budapest-2026',
    title: 'MMA Bellator – Budapest Gála',
    category: 'MMA',
    date: '2026-06-27',
    location: 'Budapest, Magyarország',
    venue: 'BOK Hall',
    image: '/images/event-mma-budapest.jpg',
    priceFrom: 8000,
    priceTo: 65000,
    currency: 'HUF',
    description: 'A Bellator MMA Budapest-gálája a BOK Hallban – hazai harcosok a világ legjobb MMA-szervezetének kártyáján. Teli est izgalmas mérkőzésekkel.',
    partners: [
      { name: 'Eventim.hu', url: 'https://www.eventim.hu', priceFrom: 8000, priceTo: 65000, note: 'Magyar platform' },
      { name: 'Interticket', url: 'https://www.interticket.com', priceFrom: 8500, priceTo: 68000, note: 'Magyar platform' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 10000, priceTo: 78000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '16',
    slug: 'uci-track-cycling-world-cup-2026',
    title: 'UCI Pályakerékpár Világkupa',
    category: 'Kerékpározás',
    date: '2026-10-17',
    location: 'Glasgow, Skócia',
    venue: 'Sir Chris Hoy Velodrome',
    image: '/images/event-track-cycling.jpg',
    priceFrom: 6000,
    priceTo: 45000,
    currency: 'HUF',
    description: 'A pályakerékpározás világkupájának egyik fordulója – a világ leggyorsabb kerékpárosai vetélkednek a velodromban. Szédületes sebesség és precizitás.',
    partners: [
      { name: 'AXS Tickets UK', url: 'https://www.axs.com', priceFrom: 6000, priceTo: 45000, note: 'Viszonteladói platform' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 7000, priceTo: 50000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '17',
    slug: 'ferencvaros-europa-league-2026',
    title: 'Ferencváros TC – Európa Liga Csoportkör',
    category: 'Labdarúgás',
    date: '2026-09-17',
    location: 'Budapest, Magyarország',
    venue: 'Groupama Aréna',
    image: '/images/event-fradi-europa.jpg',
    priceFrom: 8000,
    priceTo: 42000,
    currency: 'HUF',
    description: 'A Ferencváros az Európa-liga csoportkörében szerepel – nézd végig, ahogy a magyar bajnok európai színpadra lép a Groupama Arénában.',
    partners: [
      { name: 'Interticket', url: 'https://www.interticket.com', priceFrom: 8000, priceTo: 42000, note: 'Magyar platform' },
      { name: 'Eventim.hu', url: 'https://www.eventim.hu', priceFrom: 9000, priceTo: 45000, note: 'Magyar platform' },
      { name: 'StubHub', url: 'https://www.stubhub.com', priceFrom: 12000, priceTo: 58000, note: 'Viszonteladói árak' },
    ],
  },
  {
    id: '18',
    slug: 'volleyball-nations-league-budapest-2026',
    title: 'Röplabda Nemzetek Ligája – Budapest',
    category: 'Röplabda',
    date: '2026-06-06',
    location: 'Budapest, Magyarország',
    venue: 'SPAR Budapest Classic Csarnok',
    image: '/images/event-volleyball-budapest.jpg',
    priceFrom: 3000,
    priceTo: 20000,
    currency: 'HUF',
    description: 'A röplabda Nemzetek Ligájának budapesti fordulója – hazai közönség előtt játszik a magyar válogatott a világ legjobb csapatai ellen.',
    partners: [
      { name: 'Interticket', url: 'https://www.interticket.com', priceFrom: 3000, priceTo: 20000, note: 'Magyar platform' },
      { name: 'Eventim.hu', url: 'https://www.eventim.hu', priceFrom: 3500, priceTo: 22000, note: 'Magyar platform' },
    ],
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('hu-HU').format(price) + ' Ft'
}

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr)
  return new Intl.DateTimeFormat('hu-HU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(date)
}

